name: 'analytics_platform'
version: '1.0.0'
profile: 'analytics_platform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  analytics_platform:
    staging:
      +materialized: view
      +schema: staging
    ods:
      +materialized: table
      +schema: ods
    marts:
      +materialized: table
      +schema: marts
