analytics_platform:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('WAREHOUSE_DB_HOST') }}"
      user: "{{ env_var('WAREHOUSE_DB_USER') }}"
      password: "{{ env_var('WAREHOUSE_DB_PASSWORD') }}"
      port: "{{ env_var('WAREHOUSE_DB_PORT') | int }}"
      dbname: "{{ env_var('WAREHOUSE_DB_NAME') }}"
      schema: analytics
      threads: 4
      keepalives_idle: 0
