version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: yellow_taxi_trips
        description: Raw yellow taxi trip records loaded from the NYC TLC dataset.
        columns:
          - name: tpep_pickup_datetime
            tests:
              - not_null
          - name: pulocationid
            tests:
              - not_null
          - name: dolocationid
            tests:
              - not_null
      - name: taxi_zone_lookup
        description: Taxi zone lookup table.
        columns:
          - name: locationid
            tests:
              - not_null
              - unique

models:
  - name: stg_yellow_taxi
    description: Cleaned yellow taxi trips.
    columns:
      - name: vendor_id
        tests:
          - not_null
      - name: pickup_datetime
        tests:
          - not_null
      - name: dropoff_datetime
        tests:
          - not_null
      - name: pickup_location_id
        tests:
          - not_null
      - name: dropoff_location_id
        tests:
          - not_null
      - name: payment_type
        tests:
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6]
      - name: total_amount
        tests:
          - not_null

  - name: stg_taxi_zone_lookup
    description: Cleaned taxi zone lookup table.
    columns:
      - name: location_id
        tests:
          - not_null
          - unique
